project_id = "iycbpeujxgwcsmelvwdw"

[functions.admin-users]
verify_jwt = false

[functions.admin-notify]
verify_jwt = false

[functions.admin-withdrawals]
verify_jwt = true

[functions.admin-tasks]
verify_jwt = true

[functions.admin-countries]
verify_jwt = true
