/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardWorkerRouteImport } from './routes/dashboard.worker'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as DashboardWorkerRejectedRouteImport } from './routes/dashboard.worker.rejected'
import { Route as DashboardWorkerCompletedRouteImport } from './routes/dashboard.worker.completed'
import { Route as DashboardWorkerAppliedRouteImport } from './routes/dashboard.worker.applied'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWorkerRoute = DashboardWorkerRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/auth/forgot',
  path: '/auth/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkerRejectedRoute = DashboardWorkerRejectedRouteImport.update({
  id: '/rejected',
  path: '/rejected',
  getParentRoute: () => DashboardWorkerRoute,
} as any)
const DashboardWorkerCompletedRoute =
  DashboardWorkerCompletedRouteImport.update({
    id: '/completed',
    path: '/completed',
    getParentRoute: () => DashboardWorkerRoute,
  } as any)
const DashboardWorkerAppliedRoute = DashboardWorkerAppliedRouteImport.update({
  id: '/applied',
  path: '/applied',
  getParentRoute: () => DashboardWorkerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/dashboard/worker': typeof DashboardWorkerRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/worker/applied': typeof DashboardWorkerAppliedRoute
  '/dashboard/worker/completed': typeof DashboardWorkerCompletedRoute
  '/dashboard/worker/rejected': typeof DashboardWorkerRejectedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/dashboard/worker': typeof DashboardWorkerRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/worker/applied': typeof DashboardWorkerAppliedRoute
  '/dashboard/worker/completed': typeof DashboardWorkerCompletedRoute
  '/dashboard/worker/rejected': typeof DashboardWorkerRejectedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/dashboard/worker': typeof DashboardWorkerRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/worker/applied': typeof DashboardWorkerAppliedRoute
  '/dashboard/worker/completed': typeof DashboardWorkerCompletedRoute
  '/dashboard/worker/rejected': typeof DashboardWorkerRejectedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/sitemap.xml'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/dashboard/worker'
    | '/dashboard/'
    | '/dashboard/worker/applied'
    | '/dashboard/worker/completed'
    | '/dashboard/worker/rejected'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/dashboard/worker'
    | '/dashboard'
    | '/dashboard/worker/applied'
    | '/dashboard/worker/completed'
    | '/dashboard/worker/rejected'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/sitemap.xml'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/dashboard/worker'
    | '/dashboard/'
    | '/dashboard/worker/applied'
    | '/dashboard/worker/completed'
    | '/dashboard/worker/rejected'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/worker': {
      id: '/dashboard/worker'
      path: '/worker'
      fullPath: '/dashboard/worker'
      preLoaderRoute: typeof DashboardWorkerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/auth/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/worker/rejected': {
      id: '/dashboard/worker/rejected'
      path: '/rejected'
      fullPath: '/dashboard/worker/rejected'
      preLoaderRoute: typeof DashboardWorkerRejectedRouteImport
      parentRoute: typeof DashboardWorkerRoute
    }
    '/dashboard/worker/completed': {
      id: '/dashboard/worker/completed'
      path: '/completed'
      fullPath: '/dashboard/worker/completed'
      preLoaderRoute: typeof DashboardWorkerCompletedRouteImport
      parentRoute: typeof DashboardWorkerRoute
    }
    '/dashboard/worker/applied': {
      id: '/dashboard/worker/applied'
      path: '/applied'
      fullPath: '/dashboard/worker/applied'
      preLoaderRoute: typeof DashboardWorkerAppliedRouteImport
      parentRoute: typeof DashboardWorkerRoute
    }
  }
}

interface DashboardWorkerRouteChildren {
  DashboardWorkerAppliedRoute: typeof DashboardWorkerAppliedRoute
  DashboardWorkerCompletedRoute: typeof DashboardWorkerCompletedRoute
  DashboardWorkerRejectedRoute: typeof DashboardWorkerRejectedRoute
}

const DashboardWorkerRouteChildren: DashboardWorkerRouteChildren = {
  DashboardWorkerAppliedRoute: DashboardWorkerAppliedRoute,
  DashboardWorkerCompletedRoute: DashboardWorkerCompletedRoute,
  DashboardWorkerRejectedRoute: DashboardWorkerRejectedRoute,
}

const DashboardWorkerRouteWithChildren = DashboardWorkerRoute._addFileChildren(
  DashboardWorkerRouteChildren,
)

interface DashboardRouteChildren {
  DashboardWorkerRoute: typeof DashboardWorkerRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardWorkerRoute: DashboardWorkerRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
