// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iycbpeujxgwcsmelvwdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5Y2JwZXVqeGd3Y3NtZWx2d2R3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIwNTI3OTQsImV4cCI6MjA5NzYyODc5NH0.Wd7a_Xqa4psDNPn8aTcYk_wGi59O3Hw_tGLOJRUQZ6c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== "undefined" ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});